[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x282a35"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.normal]
black = "0x000000"
blue = "0xcaa9fa"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[cursor]
style = "Beam"
vi_mode_style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Liga SFMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Shift|Control"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["--login"]
program = "/bin/fish"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 1
title = "Alacritty"

[window.padding]
x = 8
y = 8
