# Set a new prefix / leader key.
set -g prefix C-a
bind C-a send-prefix

# Remove delay when switching between Vim modes.
set -sg escape-time 10

# Start window numbering at 1
set -g base-index 1

# Enable color support inside of tmux.
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Default shell
set-option -g default-shell "/bin/bash"

# Binds
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind k select-pane -U
bind h select-pane -L
bind j select-pane -D
bind l select-pane -R

bind Down resize-pane -D 5
bind Up resize-pane -U 5
bind Left resize-pane -L 5
bind Right resize-pane -R 5

bind-key C-j resize-pane -D
bind-key C-k resize-pane -U
bind-key C-h resize-pane -L
bind-key C-l resize-pane -R

set-option -g mouse on
